//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAT_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public string InventiryName { get; set; }
        public string InventroyDescription { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual InventoryImage InventoryImage { get; set; }
    }
}
